defaults:
  - hydra: default
  - logger: mlflow
  # choose configuration from the experiment folder
  - /experiment: evaluate_cbm_top_k # evaluate_cbm # predict # predict_on_train # train
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: ???

trainer:
  enable_checkpointing: True
  max_epochs: 20
  callbacks: ???

model:
  lr_backbone: ???
  lr_class_head: ???
  bottleneck_num_classes: ???

data:
  batch_size: ???
  num_workers: 10
